### ISSUE TITLE
Syntax highlight preview window

### ISSUE THREAD

**Issue by jalvesaq** [ncm2/float-preview.nvim#15]
Thanks for this plugin! I'm integrating it with [Nvim-R](https://github.com/jalvesaq/Nvim-R) and I would like to syntax highlight the preview window, such as in the image below:

![floatpreview](https://user-images.githubusercontent.com/891655/81593628-1da5bd00-9396-11ea-9c5f-5f169ac8964e.png)

I had to do a small change in `autoload/float_preview.vim` to get the above screenshot. I replaced the line 85 with:

```
        if exists('b:float_syntax')
            call nvim_buf_set_option(s:buf, 'syntax', b:float_syntax)
        else
            call nvim_buf_set_option(s:buf, 'syntax', 'OFF')
        endif
```

Could you, please, support either a buffer variable as in the example above or a global variable, perhaps a dictionary with the format `{'filetype': 'syntaxname'}`?

**Comment by jalvesaq** [comment]
Maybe it's better if I support float windows directly... So, I'm closing this issue.
Thank you for your code! I will use it to help me to use floating windows in Nvim-R.

**Comment by wbthomason** [comment]
I would like to request that `float-preview` actually do support the changes requested above, or something similar. I'd also like to bring to attention the Neovim functions `vim.lsp.util.open_floating_preview` and `vim.lsp.util.fancy_floating_markdown`, which seem like they would make this easier. They are only in the `master` version right now, however.
