### ISSUE TITLE
neovim always prompt "Save change to "Untitled"

### ISSUE THREAD

**Issue by tracyone** [ncm2/float-preview.nvim#3]
minimal vimrc:

```vim
let g:buf = nvim_create_buf(0, 1)
call nvim_buf_set_lines(g:buf, 0, -1, 0, [])
call nvim_buf_set_option(g:buf, 'syntax', 'OFF')
set confirm
```

**first three line are from your plugin:float-preview.nvim**

reproduce step

```bash
nvim -u minimal_vimrc file_do_not_exist
```

then

```
:q 
```

 or 

```
:q! 
```

neovim will prompt "Save change to "Untitled"

**But with following minimal vimrc**

```vim
set confirm
```

neovim exit without any  promt

**Comment by roxma** [comment]
hmm...

Cannot reproduce

**Comment by tracyone** [comment]
Please pay attention to  **file_do_not_exist**, mean you create a new file using neovim

**Comment by roxma** [comment]
https://asciinema.org/a/233413

[![asciicast](https://asciinema.org/a/233413.svg)](https://asciinema.org/a/233413)

**Comment by tracyone** [comment]
close. It is a issue of neovim.I just updated neovim and this issue was solved
