### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by mrded** [ncm2/float-preview.nvim#6]
nvim v.0.3.7

I've following plugins installed:

```
Plug 'ncm2/ncm2'
Plug 'ncm2/float-preview.nvim'
```

While opening vim, it's giving me following error:

> Error detected while processing ~/.vim/plugged/float-preview.nvim/plugin/float_preview.vim:
line   14:
E216: No such group or event: CompleteChanged * call float_preview#_menu_popup_changed()
Press ENTER or type command to continue

I think it will be nice to have some instructions how to install it.

Thanks.

**Comment by butterflyfish** [comment]
@mrded it needs nvim v0.4

**Comment by mrded** [comment]
Wow, it's beautiful! Thank you!
