### ISSUE TITLE
Preview is not docked, even with `let g:float_preview#docked = 1`

### ISSUE THREAD

**Issue by nemanjan00** [ncm2/float-preview.nvim#7]
![2019-07-20-143915_709x269_scrot](https://user-images.githubusercontent.com/448151/61578786-2b830c80-aafc-11e9-9b97-f63262605c6d.png)

As you can see, I do have docked set to 1

But, when I type, this is what I get. 
![2019-07-20-143946_1224x487_scrot](https://user-images.githubusercontent.com/448151/61578792-3fc70980-aafc-11e9-9a29-d85e7e3b0efd.png)

Any ideas?

**Comment by roxma** [comment]
The floating window in your screenshort is not opened by this plugin.
